import type { RecordExportInput } from '@/contracts/services';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatGeneratedAt(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  const hh = String(date.getHours()).padStart(2, '0');
  const mm = String(date.getMinutes()).padStart(2, '0');
  return `${y}-${m}-${d} ${hh}:${mm}`;
}

function statusLabel(status: string): string {
  switch (status) {
    case 'given':
      return 'Given';
    case 'skipped':
      return 'Skipped';
    case 'overdue':
      return 'Overdue';
    case 'due':
      return 'Due';
    case 'upcoming':
      return 'Upcoming';
    default:
      return status;
  }
}

/**
 * Pure HTML builder for the clinic record card PDF.
 * Unit-testable / snapshot-testable without native modules.
 */
export function buildHtml(input: RecordExportInput): string {
  const { child, items, summary, scheduleSource, generatedAt } = input;

  const rows = items
    .map((item) => {
      const given =
        item.record?.status === 'given' && item.record.givenDate
          ? escapeHtml(item.record.givenDate)
          : '—';
      const note = item.record?.note ? escapeHtml(item.record.note) : '—';
      return `<tr>
  <td>${escapeHtml(item.dose.visitLabel)}</td>
  <td>${escapeHtml(item.dose.shortName)} — ${escapeHtml(item.dose.doseLabel)}</td>
  <td>${escapeHtml(item.dueDate)}</td>
  <td>${escapeHtml(statusLabel(item.status))}</td>
  <td>${given}</td>
  <td>${note}</td>
</tr>`;
    })
    .join('\n');

  const sex =
    child.sex === 'male' ? 'Male' : child.sex === 'female' ? 'Female' : 'Unspecified';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Kati — Immunization record</title>
<style>
  @page { margin: 16mm; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    color: #122033;
    font-size: 11pt;
    line-height: 1.4;
  }
  h1 { font-size: 18pt; margin: 0 0 4pt; }
  h2 { font-size: 12pt; margin: 18pt 0 8pt; font-weight: 600; }
  .meta { color: #5a6b7d; font-size: 10pt; margin: 0 0 2pt; }
  .summary { margin: 12pt 0; padding: 10pt 12pt; background: #f3f7fb; border-radius: 6pt; }
  .summary span { display: inline-block; margin-right: 14pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 8pt; }
  th, td { border: 1px solid #d5dee8; padding: 6pt 7pt; text-align: left; vertical-align: top; }
  th { background: #e8eef5; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.03em; }
  td { font-size: 10pt; }
  .disclaimer {
    margin-top: 20pt;
    padding-top: 10pt;
    border-top: 1px solid #d5dee8;
    font-size: 9pt;
    color: #5a6b7d;
  }
</style>
</head>
<body>
  <h1>Immunization record</h1>
  <p class="meta">Generated by Kati · ${escapeHtml(formatGeneratedAt(generatedAt))}</p>

  <h2>Child</h2>
  <p class="meta"><strong>${escapeHtml(child.name)}</strong></p>
  <p class="meta">Date of birth: ${escapeHtml(child.birthDate)}</p>
  <p class="meta">Sex: ${escapeHtml(sex)}</p>

  <div class="summary">
    <span><strong>${summary.givenCount}</strong> / ${summary.totalDoses} given</span>
    <span><strong>${summary.overdueCount}</strong> overdue</span>
    <span><strong>${summary.dueCount}</strong> due</span>
    <span>${Math.round(summary.completion * 100)}% complete</span>
  </div>

  <h2>Doses</h2>
  <table>
    <thead>
      <tr>
        <th>Visit</th>
        <th>Vaccine</th>
        <th>Due</th>
        <th>Status</th>
        <th>Given</th>
        <th>Note</th>
      </tr>
    </thead>
    <tbody>
${rows}
    </tbody>
  </table>

  <p class="disclaimer">
    Schedule source: ${escapeHtml(scheduleSource)}.
    Kati is a record-keeping aid, not medical advice — always follow your clinic’s guidance.
    This document was generated on-device; nothing was uploaded.
  </p>
</body>
</html>`;
}
